services:
  flaskservice:
    build: backend
    # not required since we have a nginx reverse proxy now
    # ports:
    #   - "5000:5000"
    networks:
      - mynetwork
  
  web:
    build: nginx
    ports:
    - "80:80"
    networks:
      - mynetwork
  
  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  mynetwork:
  