apiVersion: skaffold/v3
kind: Config

build:
  artifacts:
    - image: flaskservice
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: reactui
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: web
      context: nginx
      docker:
        dockerfile: Dockerfile 
      
manifests:
  rawYaml:
    - .k8s/*.yml
        
deploy:
    # In case we enable status check, this will be the timeout till which skaffold will wait
    statusCheckDeadlineSeconds: 600
    # Using kubectl as our deployer
    kubectl: {}
        # Location to our yaml files
        # Refer https://skaffold.dev/docs/references/yaml/ for more options
        